config/routes.rb
Rails.application.routes.draw do
  get ':id/destroy', to: 'users#destroy', as: :custom_destroy_user
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
	enum role: { admin: 0, user: 1, guest: 2 }
	has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Pagy::Backend
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
    if params[:role].present?
      @users = @users.where(role: params[:role])
    end

    @pagy, @users = pagy(@users)
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :role, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	include Pagy::Frontend
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: @user) do |form| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h4>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :role %>
    <%= form.select :role, User.roles.keys.map { |role| [role.humanize, role] }, {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: 'form-control-file' %>
  </div>

  <%= form.submit 'Save', class: 'btn btn-primary' %>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>First name:</strong>
    <%= user.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= user.last_name %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= user.role %>
  </p>

</div>

app/views/users/edit.html.erb
<div class="container">
  <h1><%= @user.new_record? ? 'New User' : 'Edit User' %></h1>
  <%= render 'form' %>
  <%= link_to 'Back', users_path, class: 'btn btn-secondary' %>
</div>

app/views/users/index.html.erb
<div class="container">
  <h1>All Users</h1>
  <%= form_with(url: users_path, method: "get") do %>
    <%= select_tag(:role, options_for_select([["All", 'all']] + User.roles.to_a, params[:role]), onchange: 'this.form.submit();') %>
  <% end %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Role</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.role.humanize %></td>
          <td>
            <%= link_to 'Show', user, class: 'btn btn-primary btn-sm' %>
            <%= link_to 'Edit', edit_user_path(user), class: 'btn btn-secondary btn-sm' %>
            <%= link_to 'Destroy', custom_destroy_user_path(user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'New User', new_user_path, class: 'btn btn-success' %>
  <div class="pag-bar mt-5 pt-5">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <h1><%= @user.new_record? ? 'New User' : 'Edit User' %></h1>
  <%= render 'form' %>
  <%= link_to 'Back', users_path, class: 'btn btn-secondary' %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>



<div class="container">
  
<h1>User Details</h1>

  <% if @user.image.attached? %>
    <%= image_tag(@user.image, :size =>'400x200') %>
  <% end %>
  <dl class="row">
    <dt class="col-sm-3">First Name:</dt>
    <dd class="col-sm-9"><%= @user.first_name %></dd>
    
    <dt class="col-sm-3">Last Name:</dt>
    <dd class="col-sm-9"><%= @user.last_name %></dd>
    
    <dt class="col-sm-3">Role:</dt>
    <dd class="col-sm-9"><%= @user.role.humanize %></dd>
  </dl>
  <%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-primary' %>
  <%= link_to 'Back', users_path, class: 'btn btn-secondary' %>
</div>